local L = AutoMarkerLocale

TrinketMenu.packDescriptions = {}

TrinketMenu.packDescriptions[L["Naxxramas"]] = {
	[1] = { packName = "spider_entrance_patrol", desc = "Spider Entrance Patrol [10x Infectious Skitterer]" },
	[2] = { packName = "spider_entrance_right", desc = "Spider Entrance Right [1x Venom Stalker, 2x Dread Creeper, 3x Carrion Spinner]" },
	[3] = { packName = "spider_entrance_left", desc = "Spider Entrance Left [1x Venom Stalker, 2x Dread Creeper, 3x Carrion Spinner]" },
	[4] = { packName = "spider_anubrekhan_hallway", desc = "Spider Anubrekhan Hallway [1x Venom Stalker, 2x Dread Creeper, 3x Carrion Spinner]" },
	--[5] = { packName = "spider_anubrekhan", desc = "Spider Anubrekhan [1x Anub'Rekhan, 2x Crypt Guard]" },
	[5] = { packName = "boss_anub", desc = "BOSS Anub'Rekhan" },
	[6] = { packName = "spider_central_right", desc = "Spider Central Right [1x Crypt Reaver, 6x Carrion Spinner]" },
	[7] = { packName = "spider_central_patrol", desc = "Spider Central Patrol [8x Infectious Skitterer]" },
	[8] = { packName = "spider_necro_1", desc = "Spider Necro 1 [2x Necro Stalker]" },
	[9] = { packName = "spider_necro_2", desc = "Spider Necro 2 [2x Necro Stalker]" },
	[10] = { packName = "spider_faerlina_patrol", desc = "Spider Faerlina Patrol [8x Infectious Skitterer]" },
	[11] = { packName = "spider_faerlina_left_1", desc = "Spider Faerlina Left 1 [4x Naxxramas Acolyte, 1x Naxxramas Cultistz, 3x Naxxramas Cultist]" },
	[12] = { packName = "spider_faerlina_left_2", desc = "Spider Faerlina Left 2 [4x Naxxramas Acolyte, 4x Naxxramas Cultist]" },
	[13] = { packName = "spider_faerlina_left_3", desc = "Spider Faerlina Left 3 [4x Naxxramas Cultist, 4x Naxxramas Acolyte]" },
	[14] = { packName = "spider_faerlina_right_1", desc = "Spider Faerlina Right 1 [4x Naxxramas Acolyte, 4x Naxxramas Cultist]" },
	[15] = { packName = "spider_faerlina_right_2", desc = "Spider Faerlina Right 2 [4x Naxxramas Cultist, 4x Naxxramas Acolyte]" },
	[16] = { packName = "spider_faerlina_right_3", desc = "Spider Faerlina Right 3 [4x Naxxramas Acolyte, 4x Naxxramas Cultist]" },
	[17] = { packName = "boss_faerlina", desc = "BOSS Grand Widow Faerlina" },
	--[17] = { packName = "spider_faerlina", desc = "Spider Faerlina [1x Grand Widow Faerlina, 2x Naxxramas Follower, 4x Naxxramas Worshipper]" },
	[18] = { packName = "spider_final", desc = "Spider Final [4x Dread Creeper, 1x Tomb Horror]" },
	[19] = { packName = "spider_ring_ghouls_1", desc = "Spider Ring Ghouls 1" },
	[20] = { packName = "spider_ring_ghouls_2", desc = "Spider Ring Ghouls 2" },
	[21] = { packName = "spider_ring_pats", desc = "Spider Ring Pats [2x Necropolis Acolyte, 4x Necro Stalker, 4x Plagued Gargoyle]" },
	[22] = { packName = "spider_ring_acolyte_2", desc = "Spider Ring Acolyte 2 [2x Necropolis Acolyte]" },
	[23] = { packName = "spider_ring_acolyte_3", desc = "Spider Ring Acolyte 3 [2x Necropolis Acolyte]" },
	[24] = { packName = "boss_maexxna", desc = "BOSS Maexxna" },

	[25] = { packName = "military_entrance_middle", desc = "Military Entrance Middle [2x Deathknight Captain]" },
	[26] = { packName = "military_entrance_left", desc = "Military Entrance Left [1x Deathknight, 2x Risen Deathknight]" },
	[27] = { packName = "military_entrance_right", desc = "Military Entrance Right [1x Deathknight, 2x Risen Deathknight]" },
	[28] = { packName = "military_entrance_patrol", desc = "Military Entrance Patrol [1x Shade of Naxxramas, 2x Necro Knight]" },
	[29] = { packName = "military_static_1", desc = "Military Static 1 [1x Deathknight, 1x D.T. Warrior, 1x D.T. Warrior, 1x Deathknight Captain]" },
	[30] = { packName = "military_forge_captains", desc = "Military Forge Captains [2x Deathknight Captain]" },
	[31] = { packName = "military_forge_shade_patrol", desc = "Military Forge Shade Patrol [1x Shade of Naxxramas]" },
	[32] = { packName = "military_forge_shades", desc = "Military Forge Shades [2x Shade of Naxxramas, 1x Necro Knight]" },
	[33] = { packName = "military_forge_constructs", desc = "Military Forge Constructs [5x Bony Construct]" },
	[34] = { packName = "military_forge_smiths", desc = "Military Forge Smiths [4x Skeletal Smith]" },
	[35] = { packName = "military_static_2", desc = "Military Static 2 [2x Deathknight, 2x Deathknight Captain]" },
	[36] = { packName = "military_static_3", desc = "Military Static 3 [1x Deathknight, 2x D.T. Warrior, 1x Deathknight Captain]" },
	[37] = { packName = "military_upper_patrol", desc = "Military Upper Patrol [1x Deathknight, 2x D.T. Warrior]" },
	[38] = { packName = "military_static_4", desc = "Military Static 4 [2x Deathknight, 1x Deathknight Captain]" },
	[39] = { packName = "military_static_5", desc = "Military Static 5 [2x Deathknight, 1x Deathknight Captain]" },
	[40] = { packName = "military_static_6", desc = "Military Static 6 [2x Deathknight, 1x Deathknight Captain]" },
	[41] = { packName = "military_static_7", desc = "Military Static 7 [1x Deathknight, 2x D.T. Warrior, 1x Deathknight Captain]" },
	[42] = { packName = "military_horse_duo", desc = "Military Horse Duo [2x Deathknight Cavalier]" },
	[43] = { packName = "military_horse_1", desc = "Military Horse 1 [1x Deathknight Cavalier, 3x D.T. Warrior]" },
	[44] = { packName = "military_horse_2", desc = "Military Horse 2 [1x Deathknight Cavalier, 2x D.T. Warrior, 1x Doom Touched Warrior]" },
	[45] = { packName = "military_horse_3", desc = "Military Horse 3 [1x Deathknight Cavalier, 1x D.T. Warrior, 2x Risen Deathknight]" },
	[46] = { packName = "military_horse_trio", desc = "Military Horse Trio [1x Death Lord, 2x Deathknight Cavalier]" },
	[47] = { packName = "military_horse_4", desc = "Military Horse 4 [1x Deathknight Cavalier, 2x D.T. Warrior, 1x Doom Touched Warrior]" },
	[48] = { packName = "boss_razuvious", desc = "BOSS Instructor Razuvious" },
	--["military_razuvious"] = "Military Razuvious [1x Deathknight Understudy, left far, 1x Deathknight Understudy, right far, 1x Deathknight Understudy, left close, 1x Deathknight Understudy, right close, 1x Instructor Razuvious]",
	[49] = { packName = "military_weps_1", desc = "Military Weps 1 [2x Unholy Axe]" },
	[50] = { packName = "military_weps_2", desc = "Military Weps 2 [1x Unholy Swords, 1x Unholy Axe]" },
	[51] = { packName = "military_weps_3", desc = "Military Weps 3 [1x Unholy Swords, 1x Unholy Axe]" },
	[52] = { packName = "military_weps_4", desc = "Military Weps 4 [1x Unholy Staff, 1x Unholy Axe]" },
	[53] = { packName = "military_weps_5", desc = "Military Weps 5 [2x Unholy Staff]" },
	--[53] = { packName = "military_gothik_horses", desc = "Military Gothik Horses [2x Deathknight Cavalier]" },
	--[54] = { packName = "military_gothik_shade", desc = "Military Gothik Shade [1x Shade of Naxxramas, 2x Necro Knight]" },
	--[55] = { packName = "gothick_ring_ghouls", desc = "Gothick Ring Ghouls [4x Plagued Ghoul]" },
	--[56] = { packName = "gothick_ring_horse", desc = "Gothick Ring Horse [2x Necro Knight]" },
	[54] = { packName = "boss_gothik", desc = "BOSS Gothik the Harvester" },
	[55] = { packName = "military_ring_acolyte_1", desc = "Military Ring Acolyte 1 [2x Necropolis Acolyte, 1x Deathknight Vindicator, 2x Plagued Gargoyle]" },
	[56] = { packName = "military_ring_acolyte_2", desc = "Military Ring Acolyte 2 [2x Necropolis Acolyte]" },
	[57] = { packName = "military_ring_ghouls1", desc = "Military Ring Ghouls1" },
	[58] = { packName = "military_ring_acolyte_3", desc = "Military Ring Acolyte 3 [2x Necropolis Acolyte]" },
	--[61] = { packName = "military_ring_four_horsemen", desc = "Military Ring Four Horsemen [1x Highlord Mograine, 1x Thane Korth'azz, 1x Sir Zeliak, 1x Lady Blaumeux]" },
	[59] = { packName = "boss_four_horsemen", desc = "BOSS The Four Horsemen" },

	[60] = { packName = "plague_1", desc = "Plague 1 [1x Stoneskin Gargoyle (patrol), 3x Infectious Ghoul, 2x Plague Slime]" },
	[61] = { packName = "plague_2", desc = "Plague 2 [2x Plague Slime, 3x Infectious Ghoul]" },
	[62] = { packName = "plague_gargs1_pat", desc = "Plague Gargs1 Pat [1x pat]" },
	[63] = { packName = "plague_gargs1", desc = "Plague Gargs1 [1x stone1_right]" },
	[64] = { packName = "plague_gargs2", desc = "Plague Gargs2 [1x stone2_right]" },
	[65] = { packName = "plague_gargs3", desc = "Plague Gargs3 [1x stone3_right]" },
	[66] = { packName = "boss_noth", desc = "BOSS Noth the Plaguebringer" },
	[67] = { packName = "plague_ring_ghouls1", desc = "Plague Ring Ghouls1" },
	[68] = { packName = "plague_ring_ghouls2", desc = "Plague Ring Ghouls2" },
	[69] = { packName = "boss_heigan", desc = "BOSS Heigan the Unclean" },
	[70] = { packName = "boss_loatheb", desc = "BOSS Loatheb" },

	[71] = { packName = "construct_entrance", desc = "Construct Entrance [4x Patchwork Golem]" },
	[72] = { packName = "construct_entrance_patrol", desc = "Construct Entrance Patrol [2x Bile Retcher, 2x Sludge Belcher]" },
	[73] = { packName = "construct_central_left", desc = "Construct Central Left [1x Bile Retcher, 2x Patchwork Golem]" },
	[74] = { packName = "construct_central_right", desc = "Construct Central Right [1x Bile Retcher, 2x Patchwork Golem]" },
	[75] = { packName = "construct_central", desc = "Construct Central [4x Patchwork Golem]" },
	[76] = { packName = "construct_patchwerk_patrol", desc = "Construct Patchwerk Patrol [3x Bile Retcher, 1x Sludge Belcher]" },
	[77] = { packName = "construct_scientist_1", desc = "Construct Scientist 1 [1x Living Monstrosity, 4x Mad Scientist]" },
	[78] = { packName = "construct_scientist_2", desc = "Construct Scientist 2 [1x Living Monstrosity, 4x Mad Scientist]" },
	[79] = { packName = "construct_patchwerk", desc = "Construct Patchwerk [4x Patchwork Golem]" },
	[80] = { packName = "construct_scientist_3", desc = "Construct Scientist 3 [1x Living Monstrosity, 4x Mad Scientist]" },
	[81] = { packName = "construct_scientist_4", desc = "Construct Scientist 4 [1x Living Monstrosity, 4x Mad Scientist]" },
	[82] = { packName = "construct_scientist_5", desc = "Construct Scientist 5 [1x Living Monstrosity, 4x Mad Scientist]" },
	[83] = { packName = "boss_patchwerk", desc = "BOSS Patchwerk" },
	[84] = { packName = "construct_grobb_entrance", desc = "Construct Grobb Entrance [2x Stitched Spewer]" },
	[85] = { packName = "construct_grobb_left", desc = "Construct Grobb Left [2x Stitched Spewer]" },
	[86] = { packName = "construct_grobb_far", desc = "Construct Grobb Far [2x Stitched Spewer, 1x Stitched Spewer -- is this changing weekly?]" },
	[87] = { packName = "boss_grobbulus", desc = "BOSS Grobbulus" },
	[88] = { packName = "boss_gluth", desc = "BOSS Gluth" },
	[89] = { packName = "boss_thaddius", desc = "BOSS Thaddius" },

	[90] = { packName = "boss_sapphiron", desc = "BOSS Sapphiron" },
	[91] = { packName = "boss_kt", desc = "BOSS Kel'Thuzad" },
}

TrinketMenu.packDescriptions[L["Ahn'Qiraj"]] = {
	[1] = { packName = "entrance_1", desc = "Entrance 1 [4x Anubisath Sentinel]" },
	[2] = { packName = "entrance_2", desc = "Entrance 2 [4x Anubisath Sentinel]" },
	[3] = { packName = "entrance_patrols", desc = "Entrance Patrols [3x Obsidian Eradicator]" },
	[4] = { packName = "skeram", desc = "Skeram [1x Skeram, 2x Clone]" },
	[5] = { packName = "boss_skeram", desc = "BOSS The Prophet Skeram" },
	[6] = { packName = "brainwasher_1", desc = "Brainwasher 1 [1x Qiraji Brainwasher, 2x Vekniss Guardian]" },
	[7] = { packName = "warrior_1", desc = "Warrior 1 [3x Vekniss Warrior]" },
	[8] = { packName = "brainwasher_2", desc = "Brainwasher 2 [3x Vekniss Guardian, 1x Qiraji Brainwasher]" },
	[9] = { packName = "brainwasher_left", desc = "Brainwasher Left [3x Vekniss Guardian, 2x Qiraji Brainwasher]" },
	[10] = { packName = "brainwasher_right", desc = "Brainwasher Right [3x Vekniss Guardian, 2x Qiraji Brainwasher]" },
	[11] = { packName = "boss_bug_trio", desc = "BOSS Bug Trio (Vem, Princess Yauj, Lord Kri)" },
	[12] = { packName = "warrior_2", desc = "Warrior 2 [3x Vekniss Warrior]" },
	[13] = { packName = "guardian_1", desc = "Guardian 1 [6x Vekniss Guardian]" },
	[14] = { packName = "guardian_2", desc = "Guardian 2 [6x Vekniss Guardian]" },
	[15] = { packName = "guardian_3", desc = "Guardian 3 [6x Vekniss Guardian]" },
	[16] = { packName = "guardian_4", desc = "Guardian 4 [6x Vekniss Guardian]" },
	--[17] = { packName = "sartura", desc = "Sartura [3x Sartura's Royal Guard, 1x Battleguard Sartura]" },
	[17] = { packName = "boss_sartura", desc = "BOSS Battleguard Sartura" },
	[18] = { packName = "boss_fankriss", desc = "BOSS Fankriss the Unyielding" },
	[19] = { packName = "boss_viscidus", desc = "BOSS Viscidus" },
	[20] = { packName = "soldiers", desc = "Soldiers [5x Vekniss Soldier]" },
	[21] = { packName = "scorpions", desc = "Scorpions [4x Vekniss Hive Crawler]" },
	[22] = { packName = "scorpions2", desc = "Scorpions2 [2x Vekniss Hive Crawler]" },
	[23] = { packName = "lashers", desc = "Lashers [2x Vekniss Stinger, 5x Qiraji Lasher, 2x Vekniss Wasp]" },
	[24] = { packName = "boss_huhuran", desc = "BOSS Princess Huhuran" },
	[25] = { packName = "defenders", desc = "Defenders [5x Anubisath Defender]" },
	[26] = { packName = "champions", desc = "Champions [8x Qiraji Champion]" },
	[27] = { packName = "boss_twin_emperors", desc = "BOSS Twin Emperors (Vek'lor & Vek'nilash)" },
	[28] = { packName = "boss_cthun", desc = "BOSS C'Thun" },
}

TrinketMenu.packDescriptions[L["Zul'Gurub"]] = {
	[1] = { packName = "entrance_snakes_left_1", desc = "Entrance Snakes Left 1" },
	[2] = { packName = "entrance_priest_left", desc = "Entrance Priest Left" },
	[3] = { packName = "jindo_entrance_patrols", desc = "Jindo Entrance Patrols" },
	[4] = { packName = "jindo_misress_1_patrol", desc = "Jindo Misress 1 Patrol [1x jindo pull 2nd from back, left, 1x jindo pull 2nd from back, right]" },
	[5] = { packName = "jindo_mistress_2", desc = "Jindo Mistress 2" },
	[6] = { packName = "jindo_boss_pack", desc = "Jindo Boss Pack [1x 2nd from back, left, 1x 2nd from back, right]" },
	[7] = { packName = "hill_bottom_priest", desc = "Hill Bottom Priest" },
	[8] = { packName = "consolidated_bat_1", desc = "Consolidated Bat 1" },
	[9] = { packName = "consolidated_bat_2", desc = "Consolidated Bat 2" },
	[10] = { packName = "venoxis_two_axethrower", desc = "Venoxis Two Axethrower" },
	[11] = { packName = "venoxis_priest_pat", desc = "Venoxis Priest Pat [1x priest, 1x axethrower]" },
	[12] = { packName = "venoxis_room", desc = "Venoxis Room" },
	[13] = { packName = "venoxis_exit_snake_1", desc = "Venoxis Exit Snake 1" },
	[14] = { packName = "venoxis_exit_snake_2", desc = "Venoxis Exit Snake 2 [1x adder]" },
	[15] = { packName = "zanza_tower_zerks", desc = "Zanza Tower Zerks" },
	[16] = { packName = "mandokir_entrance_and_zerk", desc = "Mandokir Entrance And Zerk" },
	[17] = { packName = "mandokir_room", desc = "Mandokir Room [1x priest, 1x blooddrinker, 1x guardian, pat, 5x guardian, 6x raptors]" },
	[18] = { packName = "zanaz_witchdoctor_rtv", desc = "Zanaz Witchdoctor Rtv" },
	[19] = { packName = "madness1", desc = "Madness1" },
	[20] = { packName = "madness2", desc = "Madness2" },
	[21] = { packName = "madness3", desc = "Madness3" },
	[22] = { packName = "madness4", desc = "Madness4" },
	[23] = { packName = "thekal_pack", desc = "Thekal Pack [6x tiger, 6x tiger cub]" },
	[24] = { packName = "gaz_fish", desc = "Gaz Fish [4x croc]" },
	[25] = { packName = "thekal_zerk_panther", desc = "Thekal Zerk Panther" },
	[26] = { packName = "arlok_1", desc = "Arlok 1" },
	[27] = { packName = "arlok_2", desc = "Arlok 2" },
	[28] = { packName = "arlok_3", desc = "Arlok 3 [4x panther, 1x shadow hunter]" },
	[29] = { packName = "arlok_4", desc = "Arlok 4 [2x shadow hunter]" },
	[30] = { packName = "arlokk", desc = "Arlokk" },
	[31] = { packName = "hakkar_bottom", desc = "Hakkar Bottom [1x left zerk, 1x crocs, 1x right zerk]" },
	[32] = { packName = "hakkar_sons", desc = "Hakkar Sons" },
	[33] = { packName = "hakkar_soulflayer_1", desc = "Hakkar Soulflayer 1 [2x son, 1x flayer]" },
	[34] = { packName = "hakkar_soulflayer_2", desc = "Hakkar Soulflayer 2 [2x son, 1x flayer]" },
	[35] = { packName = "hakkar_large_1", desc = "Hakkar Large 1 [2x soulflayer, 2x priest]" },
	[36] = { packName = "hakkar_large_2", desc = "Hakkar Large 2 [2x soulflayer, 2x priest]" },
}

TrinketMenu.packDescriptions[L["Emerald Sanctum"]] = {
	[1] = { packName = "entrance", desc = "Entrance [1x sancutum wyrm pat, 2x s. scalebane pat, 9x s. dreamer, left, 4x s. dreamer, right, 2x s. dragonkin, right]" },
	[2] = { packName = "wyrmkin_pack_right_2", desc = "Wyrmkin Pack Right 2 [2x s. wyrmkin, 1x s. dragonkin, 3x s. dreamer]" },
	[3] = { packName = "dreamer_pack_left_2", desc = "Dreamer Pack Left 2 [1x s. wyrmkin, 9x s. dreamer]" },
	[4] = { packName = "wyrmkin_pack_left_1", desc = "Wyrmkin Pack Left 1 [2x s. dragonkin, 1x s. scalebane, 1x s. wyrmkin, 1x s. supressor]" },
	[5] = { packName = "wyrmkin_pack_left_2", desc = "Wyrmkin Pack Left 2 [4x s. dreamer, 2x s. wyrmkin, 1x s. wrym]" },
	[6] = { packName = "dreamer_pack_right_1", desc = "Dreamer Pack Right 1 [7x s. dreamer]" },
	[7] = { packName = "wyrmkin_pack_left_3", desc = "Wyrmkin Pack Left 3 [7x s. dreamer, 2x s. scalebane, 1x s. wyrmkin -- ??, 1x s. dragonkin]" },
	[8] = { packName = "dreamer_pack_end", desc = "Dreamer Pack End [1x s. dragonkin, 9x s. dreamer, 1x s. supressor]" },
	[9] = { packName = "wyrmkin_pack_right_3", desc = "Wyrmkin Pack Right 3 [5x s. dreamer, 1x s. supressor, 1x s. dragonkin, 2x s. scalebane]" },
	[10] = { packName = "solnius", desc = "Solnius [1x solnius]" },
}

TrinketMenu.packDescriptions[L["Molten Core"]] = {
	[1] = { packName = "giants1", desc = "Giants1" },
	[2] = { packName = "pats1", desc = "Pats1" },
	[3] = { packName = "boss_incindis", desc = "BOSS Incindis" },
	[4] = { packName = "giants2", desc = "Giants2" },
	--[5] = { packName = "lucifron", desc = "Lucifron" },
	[5] = { packName = "boss_lucifron", desc = "BOSS Lucifron" },
	[6] = { packName = "imp_surgers", desc = "Imp Surgers" },
	[7] = { packName = "boss_magmadar", desc = "BOSS Magmadar" },
	[8] = { packName = "giants3", desc = "Giants3" },
	[9] = { packName = "boss_gehennas", desc = "BOSS Gehennas" },
	[10] = { packName = "giants4", desc = "Giants4 [1x destroyer]" },
	[11] = { packName = "pats2", desc = "Pats2" },
	[12] = { packName = "giants5", desc = "Giants5 [2x destroyer]" },
	--[13] = { packName = "garr", desc = "Garr" },
	[13] = { packName = "boss_garr", desc = "BOSS Garr" },
	[14] = { packName = "baron_pack_1", desc = "Baron Pack 1" },
	[15] = { packName = "baron_pack_2", desc = "Baron Pack 2 before Baron" },
	[16] = { packName = "boss_baron_geddon", desc = "BOSS Baron Geddon" },
	[17] = { packName = "baron_pack_3", desc = "Baron Pack 3 before Shazzrah" },
	[18] = { packName = "boss_shazzrah", desc = "BOSS Shazzrah" },
	[19] = { packName = "baron_pack_4", desc = "Baron Pack 4" },
	[20] = { packName = "baron_pack_5", desc = "Baron Pack 5" },
	[21] = { packName = "sulfuron", desc = "Sulfuron" },
	[22] = { packName = "boss_golemagg", desc = "BOSS Golemagg the Incinerator" },
	[23] = { packName = "golemag_shadowforge_pack", desc = "Golemag Shadowforge Pack" },
	--[24] = { packName = "twin_golems", desc = "Twin Golems [1x this guy starts without the debuff]" },
	[24] = { packName = "boss_twin_golems", desc = "BOSS Twin Golems (Basalthar & Smoldaris)" },
	[25] = { packName = "shadowforge_left_1", desc = "Shadowforge Left 1 [1x pat]" },
	[26] = { packName = "shadowforge_left_2", desc = "Shadowforge Left 2" },
	[27] = { packName = "shadowforge_left_3", desc = "Shadowforge Left 3" },
	[28] = { packName = "shadowforge_left_4", desc = "Shadowforge Left 4" },
	[29] = { packName = "shadowforge_left_5", desc = "Shadowforge Left 5" },
	[30] = { packName = "shadowforge_right_1", desc = "Shadowforge Right 1 [1x blazeweaver, 1x pat]" },
	[31] = { packName = "shadowforge_right_2", desc = "Shadowforge Right 2" },
	[32] = { packName = "shadowforge_right_3", desc = "Shadowforge Right 3" },
	[33] = { packName = "shadowforge_right_4", desc = "Shadowforge Right 4" },
	[34] = { packName = "shadowforge_right_5", desc = "Shadowforge Right 5" },
	[35] = { packName = "boss_thaurissan", desc = "BOSS Sorcerer-Thane Thaurissan" },
	--[36] = { packName = "domo", desc = "Domo [4x elite, 4x healer, 1x domo]" },
	[36] = { packName = "boss_majordomo", desc = "BOSS Majordomo Executus" },
	[37] = { packName = "boss_ragnaros", desc = "BOSS Ragnaros" },
}

TrinketMenu.packDescriptions[L["Ruins of Ahn'Qiraj"]] = {
	[1] = { packName = "entrance", desc = "Entrance" },
	[2] = { packName = "entrance_pats", desc = "Entrance Pats" },
	[3] = { packName = "entrance_pats_2", desc = "Entrance Pats 2 [1x kurinaxx]" },
	[4] = { packName = "general_rajaxx", desc = "General Rajaxx" },
	[5] = { packName = "buru_path", desc = "Buru Path" },
	[6] = { packName = "buru_slimes", desc = "Buru Slimes [2x slime]" },
	[7] = { packName = "buru_eggs", desc = "Buru Eggs [6x egg, 1x buru]" },
	[8] = { packName = "resevoir", desc = "Resevoir" },
	[9] = { packName = "ossirian_room", desc = "Ossirian Room" },
}

TrinketMenu.packDescriptions[L["Blackwing Lair"]] = {
	--[1] = { packName = "bwl_razor", desc = "BWL Razor [1x razorgore, 1x grethok]" },
	[1] = { packName = "boss_razorgore", desc = "BOSS Razorgore the Untamed" },
	--[2] = { packName = "vael", desc = "Vael" },
	[2] = { packName = "boss_vaelastrasz", desc = "BOSS Vaelastrasz the Corrupt" },
	[3] = { packName = "wrym1", desc = "Wrym1" },
	[4] = { packName = "wrym2", desc = "Wrym2" },
	[5] = { packName = "supress1", desc = "Supress1 [3x taskmaster, 3x hatcher]" },
	[6] = { packName = "supress1_2", desc = "Supress1 2 [3x taskmaster, 3x hatcher]" },
	[7] = { packName = "supress2", desc = "Supress2 [3x taskmaster, 3x hatcher]" },
	[8] = { packName = "supress2_2", desc = "Supress2 2 [3x taskmaster, 3x hatcher, 1x lashlayer]" },
	[9] = { packName = "boss_lashlayer", desc = "BOSS Broodlord Lashlayer" },
	[10] = { packName = "lab1", desc = "Techies 1" },
	[11] = { packName = "lab2", desc = "Techies 2 before Firemaw" },
	[12] = { packName = "boss_firemaw", desc = "BOSS Firemaw" },
	[13] = { packName = "lab3", desc = "Techies 3" },
	[14] = { packName = "wyrmguard1", desc = "Wyrmguard1" },
	[15] = { packName = "lab4", desc = "Techies 4" },
	[16] = { packName = "lab5", desc = "Techies 5" },
	[17] = { packName = "lab6", desc = "Techies 6" },
	[18] = { packName = "lab7", desc = "Techies 7" },
	[19] = { packName = "wyrmguard2", desc = "2x Wyrmguard before Dragons" },
	[20] = { packName = "boss_ebonroc", desc = "BOSS Ebonroc" },
	[21] = { packName = "boss_flamegor", desc = "BOSS Flamegor" },
	[22] = { packName = "wyrmguard3", desc = "3x Wyrmguard before Chromaggus" },
	[23] = { packName = "boss_chromaggus", desc = "BOSS Chromaggus" },
	[24] = { packName = "boss_nefarian", desc = "BOSS Nefarian" },
}

TrinketMenu.packDescriptions[L["Tower of Karazhan"]] = {
	[1] = { packName = "kara_entrance_patrols", desc = "Kara Entrance Patrols [1x S.C. Darkbringer, 1x S.C. Rager, 1x G. Gloomwing]" },
	[2] = { packName = "kara_entrance_1", desc = "Kara Entrance 1 [3x Spectral Worker]" },
	[3] = { packName = "kara_entrance_2", desc = "Kara Entrance 2 [1x Spectral Worker, 2x S.C. Worgen]" },
	[4] = { packName = "kara_entrance_worgen_1", desc = "Kara Entrance Worgen 1 [4x S.C. Worgen, 1x S.C. Darkbringer, 1x S.C. Rager]" },
	[5] = { packName = "kara_entrance_worgen_2", desc = "Kara Entrance Worgen 2 [1x S.C. Darkbringer, 3x Gloomwing, 1x Creeper, 1x S.C. Rager, 1x S.C. Worgen]" },
	[6] = { packName = "kara_entrance_worker", desc = "Kara Entrance Worker [1x Spectral Worker]" },
	[7] = { packName = "kara_entrance_outer", desc = "Kara Entrance Outer [1x G. Gloomwing, 2x Spectral Worker]" },
	[8] = { packName = "kara_entrance_outer_2", desc = "Kara Entrance Outer 2 [1x Spectral Worker, 1x S.C. Worgen]" },
	[9] = { packName = "kara_entrance_outer_3", desc = "Kara Entrance Outer 3 [2x S.C. Rager, 2x S.C. Worgen, 1x S.C. Darkbringer]" },
	[10] = { packName = "kara_entrance_inner_2", desc = "Kara Entrance Inner 2 [1x S.C. Darkbringer, 1x V. Gloomwing]" },
	[11] = { packName = "kara_entrance_gnarlmoon", desc = "Kara Entrance Gnarlmoon [2x S.C. Rager, 3x S.C. Darkbringer, 2x S.C. Worgen]" },
	[12] = { packName = "boss_gnarlmoon", desc = "BOSS Gnarlmoon" },
	[13] = { packName = "kara_entrance_inner_1", desc = "Kara Entrance Inner 1" },
	--["gnarlmoon_owls"] = "Gnarlmoon Owls [1x blue owl 1, fake id, 1x blue owl 2, fake id, 1x red owl 1, fake id, 1x red owl 2, fake id]",
	[14] = { packName = "kara_library_1", desc = "Kara Library 1 [2x M. Mageweaver, 1x M. Suppressor, 1x M.D. Guard, 1x M. Whelp]" },
	[15] = { packName = "kara_library_patrols", desc = "Kara Library Patrols [2x M. Suppressor, 1x M.D. Guard, 1x M. Overseer]" },
	[16] = { packName = "kara_library_2", desc = "Kara Library 2 [2x M. Whelp, 1x M. Mageweaver]" },
	[17] = { packName = "kara_library_3", desc = "Kara Library 3 [4x M. Whelp, 2x M. Mageweaver, 1x M. Dragon Guard]" },
	[18] = { packName = "kara_library_4", desc = "Kara Library 4 [9x M. Whelp, 1x M. Drake]" },
	[19] = { packName = "kara_library_5", desc = "Kara Library 5" },
	[20] = { packName = "kara_library_6", desc = "Kara Library 6" },
	[21] = { packName = "kara_library_7", desc = "Kara Library 7" },
	[22] = { packName = "kara_library_8", desc = "Kara Library 8 [1x M. Suppressor, 1x M. Mageweaver, 2x M. Dragon Guard, 1x M. Drake]" },
	[23] = { packName = "incantagos_seekers", desc = "Incantagos Seekers [4x M. Ley-Seeker]" },
	[24] = { packName = "boss_incantagos", desc = "BOSS Incantagos" },
	[25] = { packName = "kara_library_upper_1", desc = "Kara Library Upper 1 [2x M. Mageweaver, 1x M. Suppressor, 2x M. Dragon Guard, 4x M. Whelp]" },
	[26] = { packName = "kara_library_upper_patrols", desc = "Kara Library Upper Patrols [1x Dragon Guard, 1x Arcane Anomaly]" },
	[27] = { packName = "kara_library_upper_2", desc = "Kara Library Upper 2 [2x M. Suppressor, 5x M. Whelp, 1x U.A. Elemental]" },
	[28] = { packName = "kara_library_upper_3", desc = "Kara Library Upper 3 [2x U.A. Elemental, 3x Arcane Overflow, 1x M. Suppressor]" },
	[29] = { packName = "kara_library_anomalus", desc = "Kara Library Anomalus [2x U.A. Elemental, 3x Arcane Overflow, 1x D.A. Elemental]" },
	[30] = { packName = "boss_anomalus", desc = "BOSS Anomalus" },
	[31] = { packName = "kara_observatory_1", desc = "Kara Observatory 1 [3x Arcane Overflow, 1x Arcane Anomaly, 1x U.A. Elemental, 1x D.A. Elemental]" },
	[32] = { packName = "kara_observatory_patrols", desc = "Kara Observatory Patrols [2x Arcane Overflow, 1x L. Arcanist, 1x M. Suppressor, 1x L. Enchanter]" },
	[33] = { packName = "kara_observatory_2", desc = "Kara Observatory 2 [1x L. Astrologist, 1x L. Arcanist, 1x L. Magus]" },
	[34] = { packName = "kara_observatory_left", desc = "Kara Observatory Left [1x L. Magus, 1x L. Enchanter, 2x Other]" },
	[35] = { packName = "kara_observatory_3", desc = "Kara Observatory 3 [1x Arcane Anomaly, 2x K.P. Golem]" },
	[36] = { packName = "kara_observatory_6", desc = "Kara Observatory 6" },
	[37] = { packName = "kara_echo_pre_1", desc = "Kara Echo Pre 1 [2x L. Arcanist, 2x L. Magus, 1x L. Astrologist]" },
	[38] = { packName = "kara_echo_pre_2_1", desc = "Kara Echo Pre 2 1 [1x arcane anomaly, 1x magus, 1x Crumbling Protector]" },
	[39] = { packName = "kara_echo_pre_2_2", desc = "Kara Echo Pre 2 2 [1x Crumbling Protector, 1x L. Astrologist, 1x L. Enchanter, 1x L. Arcanist]" },
	[40] = { packName = "kara_chess_1", desc = "Kara Chess 1 [1x Arcane Overflow, 1x L. Astrologist, 1x Crumbling Protector, 1x L. Enchanter, 1x K.P. Golem]" },
	[41] = { packName = "kara_chess_2", desc = "Kara Chess 2 [1x D.A. Elemental, 1x L. Astrologist, 1x L. Magus]" },
	[42] = { packName = "kara_chess_3", desc = "Kara Chess 3 [2x K.P. Golem, 1x L. Arcanist, 1x L. Magus, 1x Crumbling Protector]" },
	--["kara_chess"] = "Kara Chess", hidden since we have our own boss version
	[43] = { packName = "boss_chess", desc = "BOSS Chess" },
	[44] = { packName = "kara_foyer_1", desc = "Kara Foyer 1 [1x L. Arcanist, 1x L. Enchanter, 1x L. Magus, 1x L. Astrologist]" },
	[45] = { packName = "kara_foyer_2", desc = "Kara Foyer 2 [1x L. Magus, 1x L. Enchanter, 1x L. Arcanist, 1x L. Astrologist]" },
	[46] = { packName = "kara_foyer_3", desc = "Kara Foyer 3 [2x Forgotten Echo]" },
	[47] = { packName = "kara_roof", desc = "Kara Roof [3x Forgotten Echo]" },
	[48] = { packName = "kara_upper_demon_1", desc = "Kara Upper Demon 1 [1x destroyer, 2x invader]" },
	[49] = { packName = "kara_upper_demon_2", desc = "Kara Upper Demon 2 [2x Desolate Invader, 1x Desolate Destroyer]" },
	[50] = { packName = "kara_upper_demon_3", desc = "Kara Upper Demon 3 [2x Desolate Invader, 1x Desolate Destroyer]" },
	[51] = { packName = "kara_upper_demon_4", desc = "Kara Upper Demon 4 [1x invader, 2x destroyer, 1x Ima'ghaol]" },
	[52] = { packName = "darkbinders1", desc = "Darkbinders1 [1x Warbringer Overseer, 2x Draenei Darkbinder, 1x souleater]" },
	[53] = { packName = "village_1", desc = "Village 1 [1x Warbringer Overseer]" },
	[54] = { packName = "village_2", desc = "Village 2 [1x Doomguard Annihilator, 2x Darkflame Imp]" },
	[55] = { packName = "village_3", desc = "Village 3 [3x Draenei Darkbinder, 4x Draenei Worshipper]" },
	[56] = { packName = "infernal_2", desc = "Infernal 2 [1x infernal, 4x imp]" },
	[57] = { packName = "boss_sanv", desc = "BOSS Sanv" },
	[58] = { packName = "sanv_1", desc = "Sanv 1 [1x Draenei Darkbinder, 2x Outcast Souleater, 2x Draenei Worshipper]" },
	[59] = { packName = "sanv_2", desc = "Sanv 2 [1x Draenei Darkbinder, 1x Outcast Souleater, 7x Draenei Worshipper]" },
	[60] = { packName = "sanv_3", desc = "Sanv 3 [2x Draenei Darkbinder, 1x Outcast Souleater, 3x Draenei Worshipper]" },
	[61] = { packName = "pre_rupturan_1", desc = "Pre Rupturan 1 [1x Infernal Destroyer, 5x Darkflame Imp]" },
	--["rupturan_exile"] = "Rupturan Exile [4x crumbling exile, 1x Rupturan the Broken]",
	--["rupturan_fragments"] = "Rupturan Fragments [3x Fragment of Rupturan, fake id]",
	[62] = { packName = "boss_rupturan", desc = "BOSS Rupturan" },
	[63] = { packName = "outland_patrols", desc = "Outland Patrols" },
	[64] = { packName = "pre_kruul_1", desc = "Pre Kruul 1 [2x Doomguard Annihilator, 1x Warbringer Overseer]" },
	[65] = { packName = "pre_kruul_2", desc = "Pre Kruul 2 [6x Dreadlord Doomseeker]" },
	[66] = { packName = "boss_kruul", desc = "BOSS Kruul" },
	[67] = { packName = "mephistroth", desc = "Mephistroth [2x hellfire doomguard, fake id]" },
}
